# Generated by Django 6.0 on 2026-03-12 02:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UHIConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('consent_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('patient_abha_id', models.CharField(db_index=True, max_length=255)),
                ('hospital_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('GRANTED', 'Granted'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='GRANTED', max_length=50)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('permissions', models.JSONField(default=list)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_emergency', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'UHI Consent',
                'verbose_name_plural': 'UHI Consents',
            },
        ),
    ]
