# Generated by Django 6.0 on 2026-03-02 21:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emr', '0075_chargeitem_discount_configuration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('event_type', models.CharField(choices=[('DATA_ACCESS', 'Data Access'), ('CONSENT_GRANT', 'Consent Grant'), ('CONSENT_REVOKE', 'Consent Revoke'), ('EMERGENCY_ACCESS', 'Emergency Access'), ('FHIR_EXPORT', 'FHIR Export'), ('ANALYSIS_REQUEST', 'Analysis Request'), ('LOGIN', 'Login')], max_length=30)),
                ('actor_id', models.CharField(help_text='ABHA, doctor_id, or hospital_id of the actor', max_length=255)),
                ('patient_id', models.CharField(blank=True, default='', help_text='ABHA ID of the patient whose data was accessed', max_length=255)),
                ('resource_types', models.JSONField(default=list, help_text='FHIR resource types accessed')),
                ('consent_ref', models.UUIDField(blank=True, help_text='Reference to consent artifact that authorized this action', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(default=dict, help_text='Additional context: ip, user_agent, etc.')),
                ('prev_hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', help_text='SHA-256 hash of the previous audit log entry', max_length=64)),
                ('entry_hash', models.CharField(blank=True, help_text='SHA-256 hash of this entry (content + prev_hash)', max_length=64)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', '-timestamp'], name='care_medgem_event_t_480b98_idx'), models.Index(fields=['actor_id', '-timestamp'], name='care_medgem_actor_i_dc860e_idx'), models.Index(fields=['patient_id', '-timestamp'], name='care_medgem_patient_702c6f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedGemmaAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('input_bundle', models.JSONField(default=dict, help_text='FHIR bundle or clinical data submitted for analysis')),
                ('analysis_type', models.CharField(choices=[('report_summary', 'Report Summary'), ('trend_analysis', 'Trend Analysis'), ('ddi_check', 'Drug-Drug Interaction Check'), ('differential_diagnosis', 'Differential Diagnosis Hints'), ('soap_autofill', 'SOAP Note Autofill')], default='report_summary', max_length=30)),
                ('analysis_result', models.JSONField(default=dict, help_text='Structured AI analysis output')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('model_version', models.CharField(default='medgemma-mock-1.0', max_length=50)),
                ('is_mock', models.BooleanField(default=True, help_text='Whether this analysis was generated by mock service')),
                ('disclaimer', models.TextField(default='AI-generated suggestion. Verify clinically.', help_text='Medico-legal disclaimer (always displayed to doctors)')),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Time taken for analysis in milliseconds', null=True)),
                ('encounter', models.ForeignKey(blank=True, help_text='The clinical encounter this analysis is for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='emr.encounter')),
                ('requested_by', models.ForeignKey(help_text='Doctor who requested the analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'MedGemma Analyses',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('patient_abha_id', models.CharField(db_index=True, help_text='ABHA ID of the patient granting consent', max_length=50)),
                ('requester_id', models.CharField(help_text='ID of the doctor/hospital/patient requesting access', max_length=255)),
                ('requester_type', models.CharField(choices=[('doctor', 'Doctor'), ('hospital', 'Hospital'), ('patient', 'Patient')], max_length=20)),
                ('purpose', models.CharField(choices=[('diagnosis', 'Diagnosis'), ('second_opinion', 'Second Opinion'), ('research', 'Research'), ('emergency', 'Emergency'), ('follow_up', 'Follow Up')], max_length=30)),
                ('scope', models.JSONField(default=list, help_text='FHIR resource types allowed. e.g. ["DiagnosticReport", "Observation"]')),
                ('exclude', models.JSONField(default=list, help_text='FHIR resource types explicitly excluded. e.g. ["MentalHealthRecord"]')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(help_text='Consent expiry time')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('patient_signature', models.TextField(blank=True, default='', help_text='Patient-signed JWT claim for non-repudiation')),
                ('consent_token', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Short-lived scoped consent token', unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending')], default='ACTIVE', max_length=10)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents_granted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['patient_abha_id', 'status'], name='care_medgem_patient_0ab0cb_idx'), models.Index(fields=['consent_token'], name='care_medgem_consent_cc35ed_idx'), models.Index(fields=['requester_id', 'requester_type'], name='care_medgem_request_8122bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='FHIRExportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('patient_abha_id', models.CharField(db_index=True, help_text='ABHA ID of the patient whose records are exported', max_length=50)),
                ('bundle_json', models.JSONField(default=dict, help_text='The FHIR R5 Bundle JSON content')),
                ('fhir_version', models.CharField(choices=[('R5', 'FHIR R5'), ('R4', 'FHIR R4')], default='R5', max_length=5)),
                ('resource_types', models.JSONField(default=list, help_text='List of FHIR resource types included in this bundle')),
                ('consent_ref', models.UUIDField(blank=True, help_text='Reference to the consent artifact that authorized this export', null=True)),
                ('resource_count', models.IntegerField(default=0, help_text='Number of resources in the bundle')),
                ('requester', models.ForeignKey(help_text='User who requested the export', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['patient_abha_id', '-created_date'], name='care_medgem_patient_f763ad_idx')],
            },
        ),
    ]
