from care.utils.models.base import BaseModel
from care.emr.models.encounter import Encounter
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class MedGemmaAnalysis(BaseModel):
    """
    Stores MedGemma AI analysis results.
    In mock mode, returns realistic structured JSON without running the model.
    Every output carries a disclaimer per medico-legal requirements.
    """

    class AnalysisType(models.TextChoices):
        REPORT_SUMMARY = "report_summary", "Report Summary"
        TREND_ANALYSIS = "trend_analysis", "Trend Analysis"
        DDI_CHECK = "ddi_check", "Drug-Drug Interaction Check"
        DIFFERENTIAL_DIAGNOSIS = "differential_diagnosis", "Differential Diagnosis Hints"
        SOAP_AUTOFILL = "soap_autofill", "SOAP Note Autofill"

    class Status(models.TextChoices):
        PENDING = "PENDING", "Pending"
        PROCESSING = "PROCESSING", "Processing"
        COMPLETED = "COMPLETED", "Completed"
        FAILED = "FAILED", "Failed"

    # Context
    encounter = models.ForeignKey(
        Encounter,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        help_text="The clinical encounter this analysis is for",
    )
    requested_by = models.ForeignKey(
        User,
        null=True,
        on_delete=models.SET_NULL,
        help_text="Doctor who requested the analysis",
    )

    # Input
    input_bundle = models.JSONField(
        default=dict,
        help_text="FHIR bundle or clinical data submitted for analysis",
    )
    analysis_type = models.CharField(
        max_length=30,
        choices=AnalysisType.choices,
        default=AnalysisType.REPORT_SUMMARY,
    )

    # Output
    analysis_result = models.JSONField(
        default=dict,
        help_text="Structured AI analysis output",
    )
    status = models.CharField(
        max_length=15,
        choices=Status.choices,
        default=Status.PENDING,
    )

    # Metadata
    model_version = models.CharField(
        max_length=50,
        default="medgemma-mock-1.0",
    )
    is_mock = models.BooleanField(
        default=True,
        help_text="Whether this analysis was generated by mock service",
    )
    disclaimer = models.TextField(
        default="AI-generated suggestion. Verify clinically.",
        help_text="Medico-legal disclaimer (always displayed to doctors)",
    )
    processing_time_ms = models.IntegerField(
        null=True,
        blank=True,
        help_text="Time taken for analysis in milliseconds",
    )

    class Meta:
        ordering = ["-created_date"]
        verbose_name_plural = "MedGemma Analyses"

    def __str__(self):
        return f"MedGemma {self.external_id} - {self.analysis_type} ({self.status})"
